FROM arm32v7/python:3.9-slim

WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY iot_anomaly_detector.py .
COPY anomaly_detector.onnx .

CMD ["python", "iot_anomaly_detector.py"]
